application: lolstats
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js

- url: .*
  script: lol_stats.app

libraries:
- name: webapp2
  version: "2.5.2"
